site_name: Fiware-Device-Simulator
site_url: https://fiware-device-simulator.readthedocs.org
repo_url: https://github.com/telefonicaid/fiware-device-simulator.git
site_description: Simulator of FIWARE-compatible devices (UltraLight 2.0, JSON & NGSI)
docs_dir: doc/manuals
site_dir: html
markdown_extensions: [toc,fenced_code]
use_directory_urls: false
theme: readthedocs
extra_css: ["https://fiware.org/style/fiware_readthedocs.css"]
pages:
  - 'Home': 'index.md'
  - 'Installation': 'installation.md'
  - 'Command line tools': 'command-line-tools.md'
  - 'Simulation configuration': 'simulation-configuration.md'
  - 'FIWARE Device Simulator library': 'simulator-library.md'
